sulu_admin:
    email: "%env(SULU_ADMIN_EMAIL)%"
    forms:
        directories:
            - "%kernel.project_dir%/config/forms"
    lists:
        directories:
            - "%kernel.project_dir%/config/lists"
    resources:
        authors:
            routes:
                list: 'author.get_authors'
                detail: 'author.get_author'
sulu_core:
    locales:
        fr: Français
    translations:
        - fr